version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=SDPLabs
      - POSTGRESQL_USER=sdplabsuser
      - POSTGRESQL_PASSWORD=sdplabsuser
    ports:
      - "5441:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
